apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: yo-go-gh-gitops
  description: This is GitOps manifest for yo-go-gh   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: yo-go-gh
    backstage.io/kubernetes-id: yo-go-gh 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: lucarval-rhtap/yo-go-gh-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:yo-go-gh
