apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yo-go-gh
  janus-idp.io/tekton: yo-go-gh
  backstage.io/kubernetes-id: yo-go-gh
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yo-go-gh
resources:
- deployment.yaml
- route.yaml
- service.yaml
