apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yo-go-gh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yo-go-gh 
  name: yo-go-gh
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yo-go-gh 
